# Generated by Django 4.0.4 on 2022-05-08 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_color_size_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#', max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='rgb_code',
            field=models.CharField(default='000,000,000', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
            preserve_default=False,
        ),
    ]
