# Generated by Django 4.0.4 on 2022-05-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_color_rgb_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcategory',
            name='product_design_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_design_group_for_category', to='products.productdesigngroup'),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('product_design_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_design_category', to='products.designcategory')),
                ('product_design_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_design_group', to='products.productdesigngroup')),
            ],
            options={
                'verbose_name_plural': 'Design Categories',
            },
        ),
    ]
