# Generated by Django 4.0.4 on 2022-05-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_designcategory_product_design_group_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.design'),
            preserve_default=False,
        ),
    ]
