# Generated by Django 4.0.4 on 2022-05-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_design_options_remove_product_size_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name_plural': 'Product Sizes'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_of_product', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Colors',
            },
        ),
    ]
