# Generated by Django 4.0.4 on 2022-05-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_sizes_options_remove_product_color_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.size'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_of_product', to='products.product'),
        ),
    ]
