# Generated by Django 4.0.4 on 2022-05-11 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_images_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_code',
            field=models.CharField(default='000000', max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
    ]
