# Generated by Django 4.0.4 on 2022-05-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_main_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='relative_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
