# Generated by Django 4.0.4 on 2022-05-15 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_size_relative_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sec_code',
            field=models.CharField(default=1, max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
    ]
